name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  test_push:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libopencv-dev -y
      - run: cd src/detectorcpp
      - run: cmake .
      - run: make