name: Continuous Integration

on:
  push:
    - master

jobs:
  test_push:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Dovyski/setup-opencv-action@v1
        with:
          opencv-version: '4.0.0'
      - run: cd src/detectorcpp
      - run: cmake .
      - run: make