name: Build Status

on:
  push:
    paths:
      - 'src/detectorcpp/**'
    branches: [ master ]

jobs:
  test_push:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libopencv-dev -y
      - run: cmake .
      - run: make